### ISSUE TITLE
When using roles with new permissions admin pages not loading

### ISSUE THREAD

**Issue by ErvalhouS** [vinsol/spree_admin_roles_and_access#12]
NoMethodError (undefined method `classify' for nil:NilClass):
  spree_admin_roles_and_access (1.3.0) lib/spree/permissions.rb:60:in `find_action_and_subject'
  spree_admin_roles_and_access (1.3.0) lib/spree/permissions.rb:5:in `method_missing'
  spree_admin_roles_and_access (1.3.0) app/models/spree/permission.rb:14:in `ability'
  spree_admin_roles_and_access (1.3.0) app/models/spree/role_decorator.rb:9:in `block in ability'

**Comment by ErvalhouS** [comment]
Sorry typo in permissions :P
